# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-23 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210223_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_id',
            new_name='publish',
        ),
    ]
