# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-03-01 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210301_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='prince',
            new_name='price',
        ),
    ]
