# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210222_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.IntegerField(null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(verbose_name='密码'),
        ),
    ]
